### ISSUE TITLE
How to put back GPU support?

### ISSUE THREAD

**Issue by ajbouh** [ibuildthecloud/k3s#7]
This looks like an awesome project. I'd like to use it to control a small GPU cluster I have on my LAN.

Can you provide advice about how I might put back the GPU support? I don't mind maintaining my own fork.

**Comment by liyimeng** [comment]
@ibuildthecloud I share the same thinking as well. Why this feature is removed? It is such a need for ML applications!

**Comment by liyimeng** [comment]
@ajbouh please let me know if you have any success. I am interested in this as well.

**Comment by ibuildthecloud** [comment]
@ajbouh @liyimeng On the master branch the commits are very surgical, removing features one by one.  You could try reverting the commit removing GPU support (I really don't know which one it is because I believe it might fall under "DeviceManager," not sure).

When k8s 1.13 is released and I do the rebase for the 1.13 series I can evaluate keeping GPU support.

**Comment by ibuildthecloud** [comment]
What's on master now should support GPU to my best knowledge.  Let me know if it doesn't.  Thanks!

**Comment by liyimeng** [comment]
Thanks for the great work!

**Comment by whillas** [comment]
is this with `containerd` or `docker`? What does a pod yaml look like this:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidia-cuda/Dockerfile
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
```
from https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#using-device-plugins

?
